### ISSUE TITLE
Demos do not work out of the box

### ISSUE THREAD

**Issue by NikkyAI** [edwinRNDR/wfc#1]
There seem to be a few small issues with the provided demos

1. 
https://github.com/edwinRNDR/wfc/blob/082f85bed850c9a230cdd4cb0827a59263498f0d/wfc-core/src/main/kotlin/vox/VoxReader.kt#L283
i think the correct one would be `readBytes()`, `readAllBytes()` does not resolve

2.
https://github.com/edwinRNDR/wfc/blob/c927a53b0ac478083c690a51a26f474822ec2421/wfc-demo-openrndr/src/main/kotlin/AVDemo002.kt#L66
the type of `shadows` is not `Boolean`
to fix it locally i replaced it with `Shadows.Simple()`

3. these files are missing from the repository: https://github.com/edwinRNDR/wfc/blob/c927a53b0ac478083c690a51a26f474822ec2421/wfc-demo-openrndr/src/main/kotlin/AVDemo002.kt#L50-L53
(is this perhaps accidentally added to a local `.gitignore` ?)

with these changes i managed to run all demos, except the ones referencing missing .vox files ( `AVDemo` )

**Comment by NikkyAI** [comment]
also all the .vox files in there seem to be 0kB sized, empty

**Comment by edwinRNDR** [comment]
Hi @NikkyAI I have added the datafiles and made everything work against recent versions of OPENRNDR / DNKY
